### ISSUE TITLE
Document owned protobuf files

### ISSUE THREAD

**Issue by smuu** [rollkit/rollkit#901]
Document protobuf files in `./rollkit` and `./dalc`

`make proto-lint` should not return anything when the following types are disabled in `buf.yaml`.

```
    - COMMENT_MESSAGE
    - COMMENT_RPC
    - COMMENT_ENUM
    - COMMENT_ENUM_VALUE
    - COMMENT_SERVICE
```

<details>
<summary>make proto-lint</summary>

`docker run --rm -v ./:/workspace --workdir /workspace bufbuild/buf lint --error-format=json`
</details>

<details>
<summary>buf.yaml</summary>
```
version: v1beta1

build:
  roots:
    - proto
    - third_party/proto
lint:
  use:
    - DEFAULT
    - COMMENTS
    - FILE_LOWER_SNAKE_CASE
  except:
    - COMMENT_FIELD
    - PACKAGE_VERSION_SUFFIX
    - RPC_REQUEST_STANDARD_NAME
    - SERVICE_SUFFIX
    - UNARY_RPC
  ignore:
    - tendermint
breaking:
  use:
    - FILE
```
</details>

Note: Once this is implemented remove the types from the configuration so that the CI linter can scan for those types again.
